# Tên của quy trình tự động, sẽ hiển thị trên tab Actions của GitHub
name: Auto-generate Metadata

# Quy định khi nào quy trình này sẽ được kích hoạt
on:
  push:
    branches:
      - main  # Chạy mỗi khi có ai đó push lên nhánh main
    paths-ignore:
      - 'metadata.json' # QUAN TRỌNG: Bỏ qua nếu lần push đó chỉ thay đổi file metadata.json
                         # để tránh vòng lặp vô tận

# Định nghĩa các công việc cần làm
jobs:
  build:
    # Chạy trên một máy ảo Ubuntu mới nhất
    runs-on: ubuntu-latest
    
    # Cấp quyền cho Action để nó có thể commit và push ngược lại kho chứa
    permissions:
      contents: write

    # Các bước thực hiện
    steps:
      # Bước 1: Tải mã nguồn của bạn về máy ảo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Bước 2: Cài đặt môi trường Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Bước 3: Chạy script generate_metadata.py của bạn
      - name: Run script to generate metadata.json
        run: python generate_metadata.py

      # Bước 4: Tự động Commit và Push file metadata.json nếu nó có thay đổi
      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add metadata.json
          # Chỉ commit và push nếu thực sự có thay đổi
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update metadata.json"
            git push
          else
            echo "No changes to metadata.json. Skipping commit."
          fi